rootUrl: http://localhost:8000
gridUrl: http://127.0.0.1:4444/wd/hub
tolerance: 1
screenshotsDir: './screens'
calibrate: false

browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome

system:
    parallelLimit: 1
